cluster:
  sbatch
    --ntasks-per-node={resources.threads}
    --cpus-per-task={resources.cpus}
    --mem={resources.mem_mb}
    --job-name=smk-{rule}-{wildcards}
    --account=knightlab
default-resources:
  - time=30
  - threads=20
  - cpus=1
  - mem_mb=150000
restart-times: 0
max-jobs-per-second: 10
max-status-checks-per-second: 1
latency-wait: 60
printshellcmds: True
scheduler: greedy